[package]
name = "desktopentries"
edition = "2021"
version.workspace = true

[dependencies]
ron = "0.8.1"
freedesktop-desktop-entry = "0.7.5"
librunixeer = { path = "../librunixeer", version = "0.1.0" }
